name = "v2ray-worker"
main = "src/index.ts"
compatibility_date = "2025-12-01"
usage_model = "bundled"

# Bind your KV namespace
[[kv_namespaces]]
binding = "settings"
id = "${KV_NAME}"

[build]
command = "npm install && npm run build"
